name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Update Submodules
      run: |
        git submodule init
        git submodule update

    - name: Build OpenBLAS
      run: |
        chdir dependencies/OpenBLAS
        make
      env:
        CFLAGS: -DDYNAMIC_ARCH=1
